= KFSM Visualization Gradle Plugin

== Getting started

Plugin Id: io.jumpco.open.kfsm.gradle.viz-plugin
Version: 1.0.3

=== Gradle Groovy DSL
[source,groovy]
----
plugins {
    id 'io.jumpco.open.kfsm.gradle.viz-plugin' version '1.0.3'
}
----

[Important]
====
*Important*

- The plugin is pending approval and not yet available.
- Hopefully sorted soon.
====

== Configuration

=== Gradle Groovy DSL
[source,groovy]
----
kfsmViz {
  fsm('PacketReaderFSM') {
    input = file('src/main/kotlin/PacketReader.kt') // <1>
    isGeneratePlantUml = true // <2>
    isGenerateAsciidoc = true // <3>
    output = 'packet-reader' // <4>
    outputFolder = file('generated') // <5>
    plantUmlName = 'packet-reader-statediagram.plantuml' // <6>
    asciidocName = 'packet-reader-state-table.adoc'      // <7>
  }
}
----
<1> `input: File`: Required, fully qualified filename of relevant source file
<2> `isGeneratePlantUml: Boolean`: Required default is false
<3> `isGenerateAsciidoc: Boolean`: Required default is false
<4> `output: String`: Optional filename base. The default is the classname
<5> `outputFolder: File`: Optional directory for output file. Default is `$buildDir/generated`
<6> `plantUmlName: String`: Optional filename for plantuml output. Default is `$output.plantuml`
<7> `asciidocName: String`: Optional name of Asciidoc output file. Default is `$output.adoc`


=== Example for multiple FSM definitions
[source,groovy]
----
kfsmViz {
    fsm('PacketReaderFSM') {
        input = file('src/main/kotlin/PacketReader.kt')
        output = 'packet-reader'
        outputFolder = file('generated')
        isGeneratePlantUml = true
        isGenerateAsciidoc = true
    }
    fsm('TurnstileFSM') {
        input = file('src/main/kotlin/Turnstile.kt')
        output = 'turnstile'
        outputFolder = file('generated')
        isGeneratePlantUml = true
        isGenerateAsciidoc = true
    }
}
----

== Task

[source,bash]
----
./gradle :generateFsmViz
----
